# Generated by Django 5.1.3 on 2024-12-22 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_categorymodel_postmodel_author_postmodel_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postmodel',
            old_name='categroy',
            new_name='category',
        ),
    ]
